<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('TeaPress Administration')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/signin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/login'), 'class' => 'form-signin'))); ?>
                <h2 class="form-signin-heading"><?php echo $this->translate('Please sign in'); ?></h2>
                <?php echo $this->formElement($this->form->get('username')->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElement($this->form->get('password')->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElement($this->form->get('token')); ?>
                <label class="checkbox">
                     <?php echo $this->formElement($this->form->get('remember')); ?> <?php echo $this->translate('Remember me'); ?>
                </label>
                <button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translate('Sign in'); ?></button>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </body>
</html>