language: php

php:
  - 5.4
  - 5.5

before_script:
  - php composer.phar install
  - composer self-update
  - composer update --prefer-source --dev
  
script:
  - phpunit --coverage-clover ./build/logs/clover.xml -c ./module/TeaBlog/test/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
