<?php $this->headTitle('Install extension') ?>

<h2>
    <?php echo $this->translate('Install extension'); ?>
</h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/module/install'), 'id' => 'form-upload'))); ?>
    <?php echo $this->formFileApcProgress(); ?>
    <div class="form-group <?php echo (count($this->form->getMessages('file')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('file')); ?>
        <?php echo $this->formElement($this->form->get('file')); ?>
        <?php echo $this->formElementErrors($this->form->get('file')); ?>
    </div>
    <div id="file-errors" class="help-block"></div>
    <div id="progress" class="help-block">
        <div class="progress progress-info progress-striped active">
            <div class="bar"></div>
        </div>
        <p></p>
    </div>
    <?php echo $this->formElement($this->form->get('token')); ?>
    <div class="buttons_action">
        <a href="<?php echo $this->url('admin/module'); ?>"><?php echo $this->translate('Cancel'); ?></a>
        <?php echo $this->formElement($this->form->get('submit')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">
    /**
     * Progress Bar functions
     */
    var progressInterval;

    function hideProgress() {
        $('#progress').hide();
    }

    function showProgress(amount, message) {
        $('#progress').show();
        $('#progress .bar').width(amount + '%');
        $('#progress > p').html(message);
        if (amount < 100) {
            $('#progress .progress')
                .addClass('active')
                .addClass('progress-info')
                .removeClass('progress-success');
        } else {
            $('#progress .progress')
                .removeClass('active')
                .removeClass('progress-info')
                .addClass('progress-success');
        }
    }

    function getProgress() {
        var url = '/admin/module/install/progress?id=' + $('#progress_key').val();
        $.getJSON(url, function(data) {
            //console.log(data);
            if (data.status && !data.status.done) {
                var value = Math.floor((data.status.current / data.status.total) * 100);
                showProgress(value, 'Uploading...');
            } else {
                showProgress(100, 'Complete!');
                clearInterval(progressInterval);
            }
        });
    }

    function startProgress() {
        showProgress(0, 'Starting upload...');
        progressInterval = setInterval(getProgress, 900);
    }
    
    $(function() {
        $('#form-upload').on('submit', function(e) {
            e.preventDefault();

            //hideFormElements();
            //hideErrors();
            hideProgress();

            if ($('#file').val() == '') {
                //showErrors('No file(s) selected');
                alert('No file(s) selected');
                return;
            }

            //$.fn.ajaxSubmit.debug = true;
            $(this).ajaxSubmit({
                target: '#output',
                success: function (response, statusText, xhr, $form) {
                    //showFormElements();
                },
                error: function(a, b, c) {
                    console.log(a, b, c);
                    //showFormElements();
                }
            });
            startProgress();
        });
    });
</script>