<?php $this->headTitle('Cache management') ?>
<h2>
    <?php echo $this->translate('Cache management'); ?>
    <?php if($this->permission()->isAuthorized('admin/cache/flushAll')): ?>
    <a class="tiny button right" href="<?php echo $this->url('admin/cache/flushAll'); ?>"><?php echo $this->translate('Flush all cache'); ?></a>
    <?php endif; ?>
</h2>

<table class="listing" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Key'); ?></th>
            <th><?php echo $this->translate('Namespace'); ?></th>
            <th width="200"><?php echo $this->translate('Action'); ?></th>
        </tr>
    </thead>
    <tbody>
         <?php if(count($this->caches) > 0): ?>
            <?php foreach($this->caches as $key => $cache): ?>
                <tr>
                    <td>
                        <?php echo $key; ?>
                    </td>
                    <td>
                        <?php if($cache['options']['namespace']): ?>
                            <?php echo $cache['options']['namespace']; ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if($this->permission()->isAuthorized('admin/cache/flush')): ?>
                            <a href="<?php echo $this->url('admin/cache/flush', array('key' => $key)); ?>"><?php echo $this->translate('Flush'); ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="4"><?php echo $this->translate('No cache'); ?></td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>