<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/config/edit', array(), true), 'class' => 'form-horizontal'))); ?>
<h2>
    <?php echo $this->translate('Configuration'); ?>
    <div class="pull-right">
        <button type="submit" class="btn btn-success"><?php echo $this->translate('Save'); ?></button>
    </div>
</h2>
<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <?php foreach($this->config->getTabs() as $tab): ?>
                <div href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading"><?php echo $this->translate($tab->getLabel()); ?></h4>
                </div>
                <?php foreach($tab->getSections() as $section): ?>
                <div href="#" class="list-group-item">
                    <a href="<?php echo $this->url('admin/config/edit', array('section' => $section->getName())); ?>"><?php echo $this->translate($section->getLabel()); ?></a>
                </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-9">
        <?php foreach($this->section->getGroups() as $group): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate($group->getLabel()); ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach($group->getFields() as $field): ?>
                <?php $element = $this->form->get($field->getName()); ?>
                <div class="form-group">
                    <div class="col-lg-3 control-label">
                    <?php echo $this->formLabel($element); ?>
                    </div>
                    <div class="col-lg-9">
                        <?php echo $this->formElement($element->setAttribute('class', 'form-control')); ?>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>