<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <?php foreach($this->config->getTabs() as $tab): ?>
                <div href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading"><?php echo $this->translate($tab->getLabel()); ?></h4>
                </div>
                <?php foreach($tab->getSections() as $section): ?>
                <div href="#" class="list-group-item">
                    <a href="<?php echo $this->url('admin/config/edit', array('section' => $section->getName())); ?>"><?php echo $this->translate($section->getLabel()); ?></a>
                </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-9">
        blablabla
    </div>
</div>