<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <?php foreach($this->config->getTabs() as $tab): ?>
                <div href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading"><?php echo $this->translate($tab->getLabel()); ?></h4>
                </div>
                <?php foreach($tab->getSections() as $section): ?>
                <div href="#" class="list-group-item">
                    <a href="<?php echo $this->url('admin/config/edit', array('section' => $section->getName())); ?>"><?php echo $this->translate($section->getLabel()); ?></a>
                </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-9">
        <form class="form-horizontal">
            <?php foreach($this->section->getGroups() as $group): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate($group->getLabel()); ?></h3>
                </div>
                <div class="panel-body">
                    <?php foreach($group->getFields() as $field): ?>
                    <div class="form-group">
                        <?php //TODO : $this->formElement($field->getElement()); ?>
                        <label for="inputEmail1" class="col-lg-3 control-label"><?php echo $this->translate($field->getLabel()); ?></label>
                        <div class="col-lg-9">
                            <input type="text" class="form-control" id="inputEmail1">
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </form>
    </div>
</div>