<?php $this->headTitle('Edit Post : ' . $this->form->get('postTitle')->getValue()); ?>
<h2><?php echo $this->translate('Edit Post : ' . $this->form->get('postTitle')->getValue()); ?></h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/blog/post/edit', array(), true)))); ?>

<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Write your blog post'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Give your blog post a title and add your content. Don\'t forget to make your title uniq.'); ?></p>
            <p><a href="#">View in your website.</a></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('postTitle'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('postSlug'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('postContent'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('postExcerpt'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Organize your contents'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Categorize your blog post to organize it &amp; set tags to permit cross-linking.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('categoryId'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('postTags'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Find them efficiently'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Set up the page title and meta description. These help you to define how this blog post shows up on search engines.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('postMetaTitle'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('postMetaDescription'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('postMetaKeywords'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Publish in the rigth way'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Control if this blog post can be viewed on your website and when it can be viewed.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('postVisibility'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Socialize it'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Aprouve comments and define how to publish your contents in all your social networks.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('postComment'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<?php echo $this->formElement($this->form->get('token')); ?>

<div class="buttonized button-bar">
    <ul class="button-group right">
        <li><a href="<?php echo $this->url('admin/blog/post'); ?>" class="tiny button none">Cancel</a></li>
        <li><?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'tiny button')); ?></li>
    </ul>
</div>

<?php echo $this->form()->closeTag(); ?>