
<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/blog/post/new')))); ?>
    <h2>
        <?php echo $this->translate('New Post'); ?>
        <div class="buttons_action pull-right">
            <a href="<?php echo $this->url('admin/blog/post'); ?>" class="btn btn-warning"><?php echo $this->translate('Cancel'); ?></a>
            <?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'btn btn-warning')); ?>
        </div>
    </h2>

    <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a data-toggle="tab" href="#general"><?php echo $this->translate('General'); ?></a></li>
        <li class=""><a data-toggle="tab" href="#seo"><?php echo $this->translate('SEO'); ?></a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div id="general" class="tab-pane active">
            <div class="form-group <?php echo (count($this->form->getMessages('title')) > 0) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('title')); ?>
                <?php echo $this->formElement($this->form->get('title')); ?>
                <?php echo $this->formElementErrors($this->form->get('title')); ?>
            </div>
            <div class="form-group <?php echo (count($this->form->getMessages('categoryId')) > 0) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('categoryId')); ?>
                <?php echo $this->formElement($this->form->get('categoryId')); ?>
                <?php echo $this->formElementErrors($this->form->get('categoryId')); ?>
            </div>
            <div class="form-group <?php echo (count($this->form->getMessages('description')) > 0) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('description')); ?>
                <?php echo $this->formElement($this->form->get('description')); ?>
                <?php echo $this->formElementErrors($this->form->get('description')); ?>
            </div>
        </div>
        <div id="seo" class="tab-pane">
            <div class="form-group <?php echo (count($this->form->getMessages('urlKey')) > 0) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('urlKey')); ?>
                <?php echo $this->formElement($this->form->get('urlKey')); ?>
                <?php echo $this->formElementErrors($this->form->get('urlKey')); ?>
            </div>
        </div>
    </div>
    <?php echo $this->formElement($this->form->get('token')); ?>
<?php echo $this->form()->closeTag(); ?>