<?php $this->headTitle('New Post'); ?>
<h2><?php echo $this->translate('New Post'); ?></h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/blog/post/new')))); ?>
<fieldset>
    <div class="large-3 columns">
        <h3>Write your blog post</h3>
        <p class="info">Give your blog post a title and add your content. Don't forget to make your title uniq.</p>
        <p class="info" class="info"><a href="#">View in your website.</a></p>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('postTitle'), null, null, 'tea-admin/form/row'); ?>
        
        <div class="row <?php echo (count($this->form->getMessages('postSlug')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postSlug')) . PHP_EOL; ?>
            <?php echo $this->formElement($this->form->get('postSlug')) . PHP_EOL; ?>
            <?php echo $this->formElementErrors($this->form->get('postSlug')) . PHP_EOL; ?>
        </div>
        <div class="row <?php echo (count($this->form->getMessages('postContent')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postContent')) . PHP_EOL; ?> <span class="note">Use <kbd>ALT</kbd> or <kbd>CMD</kbd> keyboard to reveal accesskeys.</span>
            <?php echo $this->formElement($this->form->get('postContent')) . PHP_EOL; ?>
            <?php echo $this->formDescription($this->form->get('postContent')) . PHP_EOL; ?>
            <?php echo $this->formElementErrors($this->form->get('postContent')) . PHP_EOL; ?>
        </div>
        <div class="row <?php echo (count($this->form->getMessages('postExcerpt')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postExcerpt')); ?>
            <?php echo $this->formElement($this->form->get('postExcerpt')); ?>
            <?php echo $this->formDescription($this->form->get('postExcerpt')) . PHP_EOL; ?>
            <?php echo $this->formElementErrors($this->form->get('postExcerpt')); ?>
        </div>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3>Organize your contents</h3>
        <p class="info">Categorize your blog post to organize it &amp; set tags to permit cross-linking.</p>
    </div>
    <div class="large-9 columns">
        <div class="row <?php echo (count($this->form->getMessages('categoryId')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('categoryId')); ?>
            <?php echo $this->formElement($this->form->get('categoryId')); ?>
            <?php echo $this->formElementErrors($this->form->get('categoryId')); ?>
        </div>
        <div class="row <?php echo (count($this->form->getMessages('postTags')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postTags')); ?>
            <?php echo $this->formElement($this->form->get('postTags')); ?>
            <?php echo $this->formElementErrors($this->form->get('postTags')); ?>
        </div>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3>Find them efficiently</h3>
        <p class="info">Set up the page title and meta description. These help you to define how this blog post shows up on search engines.</p>
    </div>
    <div class="large-9 columns">
        <div class="row <?php echo (count($this->form->getMessages('postMetaTitle')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postMetaTitle')); ?>
            <?php echo $this->formElement($this->form->get('postMetaTitle')); ?>
            <?php echo $this->formElementErrors($this->form->get('postMetaTitle')); ?>
        </div>
        <div class="row <?php echo (count($this->form->getMessages('postMetaDescription')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postMetaDescription')); ?>
            <?php echo $this->formElement($this->form->get('postMetaDescription')); ?>
            <?php echo $this->formElementErrors($this->form->get('postMetaDescription')); ?>
        </div>
        <div class="row <?php echo (count($this->form->getMessages('postMetaKeywords')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postMetaKeywords')); ?>
            <?php echo $this->formElement($this->form->get('postMetaKeywords')); ?>
            <?php echo $this->formElementErrors($this->form->get('postMetaKeywords')); ?>
        </div>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3>Publish in the rigth way</h3>
        <p class="info">Control if this blog post can be viewed on your website and when it can be viewed.</p>
    </div>
    <div class="large-9 columns">
        <div class="row <?php echo (count($this->form->getMessages('postVisibility')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postVisibility')); ?>
            <?php echo $this->formElement($this->form->get('postVisibility')); ?>
            <?php echo $this->formElementErrors($this->form->get('postVisibility')); ?>
        </div>
    </div>
    <div>
        <div class="row <?php echo (count($this->form->getMessages('postComment')) > 0) ? ' has-error' : ''; ?>">
            <?php echo $this->formLabel($this->form->get('postComment')); ?>
            <?php echo $this->formElement($this->form->get('postComment')); ?>
            <?php echo $this->formElementErrors($this->form->get('postComment')); ?>
        </div>
    </div>
</fieldset>
<?php echo $this->formElement($this->form->get('token')); ?>

<div class="buttonized button-bar">
    <ul class="button-group right">
        <li><a href="<?php echo $this->url('admin/blog/post'); ?>" class="tiny button none">Cancel</a></li>
        <li><?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'tiny button')); ?></li>
    </ul>
</div>
<?php echo $this->form()->closeTag(); ?>