<?php $this->headTitle('Edit role ' . $this->form->get('roleName')->getValue()); ?>
<h2><?php echo $this->translate('Add new role'); ?></h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/role/edit', array(), true)))); ?>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Define your role'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Give your role a title and a content. This will help you to organize your team efficiently.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('roleName'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('roleContent'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Define your permissions'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Set up the role permissions and allow or disallow your team to access and use your mods.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formResource()->setData($this->rules)->render(); ?>
    </div>
</fieldset>
<?php echo $this->formElement($this->form->get('token')); ?>

<div class="buttonized button-bar">
    <ul class="button-group right">
        <li><a href="<?php echo $this->url('admin/role'); ?>" class="tiny button none">Cancel</a></li>
        <li><?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'tiny button')); ?></li>
    </ul>
	<ul class="button-group left">
        <?php if($this->permission()->isAuthorized('admin/role/delete')): ?>
            <li><a href="<?php echo $this->url('admin/role/delete', array(), true); ?>" class="tiny button alert"><?php echo $this->translate('Delete'); ?></a></li>
		<?php endif; ?>
	</ul>
</div>

<?php echo $this->form()->closeTag(); ?>