<h2><?php echo $this->translate('List of role'); ?></h2>
<a href="<?php echo $this->url('admin/role/new'); ?>"><?php echo $this->translate('Add new role'); ?></a>
<table class="table table-striped">
    <thead>
        <th><?php echo $this->translate('Id'); ?></th>
        <th><?php echo $this->translate('Role name'); ?></th>
        <th><?php echo $this->translate('Created at'); ?></th>
        <th><?php echo $this->translate('Action'); ?></th>
    </thead>
    <tbody>
        <?php if(count($this->roles) == 0): ?>
        <tr><td colspan="5"><?php echo $this->translate('No data'); ?></td></tr>
        <?php else: ?>
            <?php foreach($this->roles as $role): ?>
            <tr>
                <td><?php echo $role->getRoleId(); ?></td>
                <td><?php echo $role->getName(); ?></td>
                <td><?php echo $role->getCreatedAt(); ?></td>
                <td><a href="<?php echo $this->url('admin/role/edit', array('id' => $role->getRoleId())); ?>"><?php echo $this->translate('Edit'); ?></a></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->roles, 'sliding', array('partial/paginator.phtml', 'admin/role')); ?>