<?php $this->headTitle('Add new role'); ?>
<h2><?php echo $this->translate('Add new role'); ?></h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/role/new')))); ?>
<fieldset>
    <div class="large-3 columns">
        <h3><?php echo $this->translate('Write your blog post'); ?></h3>
        <div class="info">
            <p><?php echo $this->translate('Give your blog post a title and add your content. Don\'t forget to make your title uniq.'); ?></p>
        </div>
    </div>
    <div class="large-9 columns">
        <?php echo $this->formRow($this->form->get('roleName'), null, null, 'tea-admin/form/row'); ?>
        <?php echo $this->formRow($this->form->get('roleContent'), null, null, 'tea-admin/form/row'); ?>
    </div>
</fieldset>
<?php echo $this->formElement($this->form->get('token')); ?>

<div class="buttonized button-bar">
    <ul class="button-group right">
        <li><a href="<?php echo $this->url('admin/role'); ?>" class="tiny button none">Cancel</a></li>
        <li><?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'tiny button')); ?></li>
    </ul>
</div>

<?php echo $this->form()->closeTag(); ?>