<h2><?php echo $this->translate('Add new role'); ?></h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/role/new')))); ?>
    <div class="form-group <?php echo (count($this->form->getMessages('name')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('name')); ?>
        <?php echo $this->formElement($this->form->get('name')); ?>
        <?php echo $this->formElementErrors($this->form->get('name')); ?>
    </div>
    <?php echo $this->formElement($this->form->get('token')); ?>
    <div class="buttons_action">
        <a href="<?php echo $this->url('admin/role'); ?>"><?php echo $this->translate('Cancel'); ?></a>
        <?php echo $this->formElement($this->form->get('submit')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>