<ul class="breadcrumbs">
    <?php foreach($this->pages as $page):
        $attribs = array(
            'id'     => $page->getId(),
            'title'  => $this->translate($page->getTitle()),
            'class'  => $page->getClass(),
            'href'   => $page->getHref(),
            'target' => $page->getTarget()
        );
        ?>
    <li>
        <a <?php //echo $this->htmlAttribs($attribs); ?>>
            <?php echo $this->escapeHtml($this->translate($page->getLabel())); ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>