<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/teapress.css')
                        ->prependStylesheet($this->basePath() . '/css/foundation.css'); ?>
    </head>
    <body class="antialiased">
        <div class="fixed">
            <nav class="top-bar" data-topbar>
                <ul class="large-2 columns">
                    <li class="name">
                        <h1><a href="#">Teapress Academy</a></h1>
                    </li>
                </ul>

                <section class="top-bar-section">
                    <ul class="right">
                        <li class="has-dropdown">
                            <a href="#">Achraf Ach Chouk</a>
                            <ul class="dropdown">
                                <li><a href="#">My profile</a></li>
                                <li><a href="#">My settings</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Logout</a></li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="left">
                        <li><a href="#">Go to website</a></li>
                    </ul>
                </section>
            </nav>
        </div>

        <div class="row">
            <div class="menu-content hide-for-small large-2 columns">
                <?php echo $this->navigation()->menu('TeaAdminNavigation')->setPartial('tea-admin/menu') . PHP_EOL; ?>
            </div>

            <div class="main-content large-10 columns">
                <?php echo $this->navigation()->breadcrumbs('TeaAdminNavigation')->setRenderInvisible()->setPartial('tea-admin/breadcrumbs') . PHP_EOL; ?>

                <?php echo $this->flashMessenger()->render('success', array('alert-box', 'success')) . PHP_EOL; ?>
                <?php echo $this->flashMessenger()->render('info', array('alert-box', 'info')) . PHP_EOL; ?>
                <?php echo $this->flashMessenger()->render('error', array('alert-box', 'alert')) . PHP_EOL; ?>
                <?php echo $this->flashMessenger()->render('default', array('alert-box', 'secondary')) . PHP_EOL; ?>

                <?php echo $this->content . PHP_EOL; ?>
            </div>
        </div>
        <?php echo $this->inlineScript()
                ->prependFile($this->basePath() . '/js/foundation.min.js')
                ->prependFile($this->basePath() . '/js/jquery.js')
                ->prependFile($this->basePath() . '/js/modernizr.js'); ?>
        <script type="text/javascript">
            $(document).foundation();
        </script>
    </body>
</html>
