<h2><?php echo $this->translate('Edit User'); ?></h2>

<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/user/edit', array(), true)))); ?>
    <?php echo $this->formElement($this->form->get('userId')); ?>
    <div class="form-group <?php echo (count($this->form->getMessages('username')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('username')); ?>
        <?php echo $this->formElement($this->form->get('username')); ?>
        <?php echo $this->formElementErrors($this->form->get('username')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('firstname')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('firstname')); ?>
        <?php echo $this->formElement($this->form->get('firstname')); ?>
        <?php echo $this->formElementErrors($this->form->get('firstname')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('lastname')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('lastname')); ?>
        <?php echo $this->formElement($this->form->get('lastname')); ?>
        <?php echo $this->formElementErrors($this->form->get('lastname')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('email')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('email')); ?>
        <?php echo $this->formElement($this->form->get('email')); ?>
        <?php echo $this->formElementErrors($this->form->get('email')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('roleId')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('roleId')); ?>
        <?php echo $this->formElement($this->form->get('roleId')); ?>
        <?php echo $this->formElementErrors($this->form->get('roleId')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('isActive')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('isActive')); ?>
        <?php echo $this->formElement($this->form->get('isActive')); ?>
        <?php echo $this->formElementErrors($this->form->get('isActive')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('password')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('password')); ?>
        <?php echo $this->formElement($this->form->get('password')); ?>
        <?php echo $this->formElementErrors($this->form->get('password')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('confirm')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('confirm')); ?>
        <?php echo $this->formElement($this->form->get('confirm')); ?>
        <?php echo $this->formElementErrors($this->form->get('confirm')); ?>
    </div>
    <?php echo $this->formElement($this->form->get('token')); ?>
    <div class="buttons_action">
        <a href="<?php echo $this->url('admin/user'); ?>"><?php echo $this->translate('Cancel'); ?></a>
        <?php echo $this->formElement($this->form->get('submit')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>