<h2><?php echo $this->translate('List of user'); ?></h2>

<table class="table table-striped">
    <thead>
        <th><?php echo $this->translate('Id'); ?></th>
        <th><?php echo $this->translate('Username'); ?></th>
        <th><?php echo $this->translate('Created at'); ?></th>
        <th><?php echo $this->translate('Action'); ?></th>
    </thead>
    <tbody>
        <?php if(count($this->users) == 0): ?>
        <tr><td colspan="5"><?php echo $this->translate('No data'); ?></td></tr>
        <?php else: ?>
            <?php foreach($this->users as $user): ?>
            <tr>
                <td><?php echo $user->getUserId(); ?></td>
                <td><?php echo $user->getUsername(); ?></td>
                <td><?php echo $user->getCreatedAt(); ?></td>
                <td><a href="<?php echo $this->url('admin/user/edit', array('id' => $user->getUserId())); ?>"><?php echo $this->translate('Edit'); ?></a></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->users, 'sliding', array('partial/paginator.phtml', 'admin/user')); ?>