<?php $this->headTitle('Admin user management') ?>
<h2>
    <?php echo $this->translate('Admin user management'); ?>
    <?php if($this->permission()->isAuthorized('admin/user/new')): ?>
    <a class="tiny button right" href="<?php echo $this->url('admin/user/new'); ?>"><?php echo $this->translate('Create new user'); ?></a>
    <?php endif; ?>
</h2>

<table class="listing" width="100%">
    <thead>
        <tr>
            <th width="10"><input type="checkbox" /></th>
            <th width="50"><?php echo $this->translate('Id'); ?></th>
            <th><?php echo $this->translate('Username'); ?></th>
            <th width="150"><?php echo $this->translate('Role'); ?></th>
            <th width="200"><?php echo $this->translate('Updated Date'); ?></th>
        </tr>
    </thead>
    <tbody>
         <?php if(count($this->users) > 0): ?>
            <?php foreach ($this->users as $user): ?>
                <tr>
                    <th><input type="checkbox" /></th>
                    <td><?php echo $user->getUserId(); ?></td>
                    <td>
                        <?php if($this->permission()->isAuthorized('admin/user/edit')): ?>
                        <a href="<?php echo $this->url('admin/user/edit', array('id' => $user->getUserId())); ?>">
                            <?php echo $user->getUsername(); ?>
                        </a>
                        <?php else: ?>
                            <?php echo $user->getUsername(); ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php echo $user->getRole()->getRoleName(); ?>
                    </td>
                    <td><?php echo $this->dateFormat(new \DateTime($user->getUserUpdated()), \IntlDateFormatter::MEDIUM, \IntlDateFormatter::MEDIUM); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="4"><?php echo $this->translate('No admin user'); ?></td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->users, 'sliding', array('partial/paginator.phtml', 'admin/user')); ?>