<?php $this->headTitle('Category Management') ?>

<h2>
    <?php echo $this->translate('Category management'); ?>
    <div class="pull-right">
        <a class="btn btn-warning" href="<?php echo $this->url('admin/blog/category/new'); ?>"><?php echo $this->translate('Create new category'); ?></a>
    </div>
</h2>

<table class="">
    <thead>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Parent'); ?></th>
    </thead>
    <tbody>
        <tr>
            <td></td>
        </tr>
    </tbody>
</table>

