<?php $this->headTitle('Category Management') ?>
<h2>
    <?php echo $this->translate('Category management'); ?>
    <a class="tiny button right" href="<?php echo $this->url('admin/blog/category/new'); ?>"><?php echo $this->translate('Create new category'); ?></a>
</h2>

<table class="listing" width="100%">
    <thead>
        <tr>
            <th width="10"><input type="checkbox" /></th>
            <th><?php echo $this->translate('Title'); ?></th>
            <th width="300"><?php echo $this->translate('Description'); ?></th>
            <th width="200"><?php echo $this->translate('Slug'); ?></th>
        </tr>
    </thead>
    <tbody>
         <?php if(count($this->categories) > 0): ?>
            <?php foreach ($this->categories as $category): ?>
                <tr>
                    <th><input type="checkbox" /></th>
                    <td>
                        <a href="<?php echo $this->url('admin/blog/category/edit', array('id' => $category->getCategoryId())); ?>">
                            <?php echo $category->getCategoryTitle(); ?>
                        </a>
                    </td>
                    <td><?php echo $category->getCategoryContent(); ?></td>
                    <td><?php echo $this->dateFormat(new \DateTime($category->getCategoryUpdated()), \IntlDateFormatter::MEDIUM, \IntlDateFormatter::MEDIUM); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="4"><?php echo $this->translate('No category'); ?></td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->categories, 'sliding', array('partial/paginator.phtml', 'admin/blog/category')); ?>