<?php $this->headTitle('Category Management') ?>

<h2>
    <?php echo $this->translate('Category management'); ?>
    <div class="pull-right">
        <a class="btn btn-warning" href="<?php echo $this->url('admin/blog/category/new'); ?>"><?php echo $this->translate('Create new category'); ?></a>
    </div>
</h2>

<table class="table table-striped">
    <thead>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Description'); ?></th>
        <th><?php echo $this->translate('Url Key'); ?></th>
        <th><?php echo $this->translate('Action'); ?></th>
    </thead>
    <tbody>
        <?php if(count($this->categories) > 0): ?>
            <?php foreach($this->categories as $category): ?>
        <tr>
            <td><?php echo $category->getTitle(); ?></td>
            <td><?php echo $category->getDescription(); ?></td>
            <td><?php echo $category->getUrlKey(); ?></td>
            <td>
                <a href="<?php echo $this->url('admin/blog/category/edit', array('id' => $category->getCategoryId())); ?>" class="btn">
                    <?php echo $this->translate('Edit'); ?>
                </a>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td><?php echo $this->translate('No category'); ?></td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->categories, 'sliding', array('partial/paginator.phtml', 'admin/blog/post')); ?>

<h2><?php echo $this->translate('Small new category form'); ?></h2>
<?php echo $this->form()->openTag($this->form->setAttributes(array('action' => $this->url('admin/blog/category')))); ?>
    <div class="form-group <?php echo (count($this->form->getMessages('title')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('title')); ?>
        <?php echo $this->formElement($this->form->get('title')); ?>
        <?php echo $this->formElementErrors($this->form->get('title')); ?>
    </div>
    <div class="form-group <?php echo (count($this->form->getMessages('parentId')) > 0) ? ' has-error' : ''; ?>">
        <?php echo $this->formLabel($this->form->get('parentId')); ?>
        <?php echo $this->formElement($this->form->get('parentId')); ?>
        <?php echo $this->formElementErrors($this->form->get('parentId')); ?>
    </div>
    <?php echo $this->formElement($this->form->get('token')); ?>
    <div class="buttons_action">
        <?php echo $this->formElement($this->form->get('submit')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>