<div class="well">
    <div class="block block-latest">
        <h4><?php echo $this->translate('Latest posts'); ?></h4>
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-unstyled">
                    <?php foreach($this->latest as $post): ?>
                    <li>
                        <a href="<?php echo $this->url('blog/post', array('name' => $post->getUrlKey())); ?>">
                            <?php echo $post->getTitle(); ?>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>